# Generated by Django 5.0 on 2023-12-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options'),
        ('shopapp', '0007_alter_product_options_product_created_by'),
    ]

    operations = [
    ]
