# Generated by Django 5.0 on 2023-12-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_merge_20231215_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
