# Generated by Django 4.2.4 on 2023-10-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
